# Generated by Django 4.2.1 on 2023-05-15 21:00

from django.db import migrations, models
from api.user.models import CustomUser


class Migration(migrations.Migration):
    def seed_data(apps,schema_editor):
        user = CustomUser(name = 'rishabh',
                        email = 'rishabh@lco.dev',
                        is_staff = True,
                        is_superuser = True,
                        phone = '7068414195',
                        gender = 'Male')
        user.set_password('1234')
        user.save()

    initial = True

    dependencies = [


    ]

    operations = [
        migrations.RunPython(seed_data),
            
    ]
