# Generated by Django 4.0.5 on 2023-05-21 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='name',
            field=models.CharField(default='Anonymous', max_length=250),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='session_token',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
